# Generated by Django 3.0.6 on 2020-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazeData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('prevTime', models.CharField(max_length=10)),
                ('numberTries', models.CharField(max_length=10)),
                ('averageTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='highscores',
            old_name='userID',
            new_name='userName',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
