# Generated by Django 3.0.6 on 2020-06-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazeData', '0003_auto_20200614_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='salt',
        ),
    ]
