# Generated by Django 3.0.6 on 2020-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazeData', '0008_auto_20200619_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscores',
            name='time',
            field=models.FloatField(),
        ),
    ]
